repos:
  - repo: local
    hooks:
      - id: verify-module-signatures
        name: Verify module signatures and version bumps
        entry: hatch run ./scripts/verify-modules-signature.py --require-signature --enforce-version-bump
        language: system
        pass_filenames: false
        always_run: true
      - id: modules-quality-checks
        name: Run modules pre-commit quality checks
        entry: ./scripts/pre-commit-quality-checks.sh
        language: system
        pass_filenames: false
