"""Fail-closed native fixture receipts; publish only allowlisted summaries."""

import collections
import hashlib
import json
import logging
import math
import os
import subprocess
import sys
from pathlib import Path
from typing import Any


STARTUP_RACES = (
    "suspended",
    "pretrace",
    "trace-stopped",
    "traced",
    "exec",
    "confined",
)
CONTROL_RACES = (
    "cancel",
    "cancel-held-stop",
    "timeout",
    "signal",
    "eof-pretrace",
    "eof-trace-stopped",
    "eof-running",
    "eof-wait",
    "eof-partial",
    "partial-timeout",
    "broker-kill",
    "cli-kill-wait",
    "isolation",
    "exec-cancel",
    "exec-eof",
    "exec-broker-kill",
    "exec-cancel-held",
    "exec-eof-held",
    "exec-broker-kill-held",
)
PROTOCOL_CASES = (
    "output-status",
    "version",
    "opcode",
    "reserved",
    "foreign-handle",
    "fixture-mode",
    "host-pid",
    "signal-selector",
    "timeout-bound",
    "unused-field",
    "fragmentation",
    "worker-limit",
    "oversize",
    "undersize",
    "authentication",
    "peer-pid",
    "peer-pidversion",
    "term-ignored",
    "runtime-trap",
    "exec-status",
    "exec-runtime-trap",
    "exec-bootstrap-trap",
    "exec-failed",
    "exec-second-image",
    "exec-modified-target",
)
BROKER_INPUTS = (
    "mach-exception-defs",
    "mach_exc_server.c",
    "mach_exc_server.h",
    "mach_exc_user.h",
    "control_mach.inc",
    "control_mach_policy.h",
    "control_mach_reply.h",
    "control_exec_policy.h",
)
SOURCE = Path(__file__).resolve().parent / "macos_managed_boundary"


JsonObject = dict[str, Any]
_LOGGER = logging.getLogger(__name__)
_FAILURE_PHASES = frozenset(
    (
        "request-authenticate",
        "request-launch",
        "request-wait",
        "request-signal",
        "request-cancel",
        "bootstrap-observe-caller",
        "bootstrap-authority",
        "bootstrap-register",
        "bootstrap-socket",
        "marker-broker",
        "marker-trace",
        "marker-output",
        "marker-exec",
        "observe-worker",
        "observe-removal",
        "cleanup",
        "isolation-launch",
        "isolation-capture",
        "isolation-peer-authority",
        "isolation-extra-connection",
        "isolation-owner-eof",
        "isolation-peer-survivor",
    )
)
_SOCKET_STATES = frozenset(
    (
        "socket_missing",
        "socket_mode_pending",
        "private_after_deadline",
        "directory_invalid",
        "socket_type_invalid",
        "socket_owner_invalid",
    )
)
_FAILURE_CLASSES = frozenset(
    (
        "TimeoutError",
        "RuntimeError",
        "CalledProcessError",
        "TimeoutExpired",
        "OSError",
        "ValueError",
        "EOFError",
        "FileNotFoundError",
        "AssertionError",
    )
)


def _require_assertions() -> None:
    """This maintainer verifier must reject optimization before native work."""
    if not __debug__:
        raise RuntimeError("native receipt validation requires enabled assertions")


def sha256(path: Path) -> str:
    """Hash exact source bytes for a public receipt digest."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _is_integer(value: object) -> bool:
    """JSON booleans cannot stand in for native integer observations."""
    return isinstance(value, int) and not isinstance(value, bool)


def valid_digest(value: object) -> bool:
    """Accept only a complete lowercase SHA-256, never untrusted text."""
    return isinstance(value, str) and len(value) == 64 and all(char in "0123456789abcdef" for char in value)


def checked_inputs(artifact: JsonObject, names: tuple[str, ...]) -> dict[str, str]:
    """Bind captured repository headers and preserve SDK/generated byte hashes."""
    inputs = artifact["build_inputs"]
    assert len(inputs) == len(names)
    assert {item["name"] for item in inputs} == set(names)
    digests = {}
    for item in inputs:
        assert valid_digest(item["sha256"])
        if item["name"].startswith("control_"):
            assert item["sha256"] == sha256(SOURCE / item["name"])
        digests[item["name"]] = item["sha256"]
    return digests


def _checked_substitutions(trial: JsonObject) -> None:
    """Both corrupted and valid foreign payloads must have been rejected."""
    assert _is_integer(trial["substitutions_checked"])
    assert trial["substitutions_checked"] == 2
    assert trial["response"]["ok"] is False
    assert trial["response"]["error"] == "signature"


def _checked_exec_wait(case: str, status: JsonObject) -> None:
    """Keep real exit status and genuine SIGTRAP delivery mandatory."""
    assert status["state"] == "exited"
    assert status["traced"] is True
    assert _is_integer(status["exit"])
    assert _is_integer(status["signal"])
    expected = {"exec-status": (37, 0), "exec-failed": (38, 0)}.get(case, (-1, 5))
    assert (status["exit"], status["signal"]) == expected


def _checked_unadmitted_exec(case: str, output: str, marker: object) -> None:
    """Failed exec and bootstrap traps cannot initialize a replacement image."""
    assert marker is None
    assert "target-initializer-ns=" not in output
    assert "target-entry" not in output
    assert "runtime-trap-was-suppressed" not in output
    if case == "exec-failed":
        assert "exec-failed" in output


def _checked_image_stop(marker: JsonObject) -> None:
    """Require a verified, released native replacement stop."""
    assert isinstance(marker, dict)
    assert _is_integer(marker["exec"])
    assert marker["exec"] > 1
    assert _is_integer(marker["verified_ns"])
    assert marker["verified_ns"] > 0
    assert marker["held"] is False


def _checked_initializer(output: str, verified_ns: int) -> None:
    """A single initializer must follow the image identity check."""
    initializers = [
        line.removeprefix("target-initializer-ns=")
        for line in output.splitlines()
        if line.startswith("target-initializer-ns=")
    ]
    assert len(initializers) == 1
    assert initializers[0].isascii()
    assert initializers[0].isdigit()
    assert int(initializers[0]) >= verified_ns


def _checked_target_output(case: str, output: str) -> None:
    """Target entry, confinement probes and later replacement attempts stay visible."""
    assert output.count("target-entry") == 1
    assert "target-denials-ok" in output
    assert "target-trap-was-suppressed" not in output
    if case == "exec-second-image":
        assert "target-second-exec" in output


def checked_exec_protocol(trial: JsonObject) -> None:
    """Require native image admission before initializers and actual trap outcomes."""
    case = trial["case"]
    if case == "exec-modified-target":
        _checked_substitutions(trial)
        return
    status, marker = trial["status"], trial["image_stop"]
    _checked_exec_wait(case, status)
    output = status["output"]
    assert isinstance(output, str)
    if case in ("exec-bootstrap-trap", "exec-failed"):
        _checked_unadmitted_exec(case, output, marker)
        return
    _checked_image_stop(marker)
    _checked_initializer(output, marker["verified_ns"])
    _checked_target_output(case, output)


def _checked_birth_identity(identity: JsonObject) -> None:
    """Require kernel birth identity and tracing of a direct owned child."""
    for field in ("pid", "ppid", "pgid", "flags", "start_sec", "start_usec"):
        assert _is_integer(identity[field])
    assert identity["pid"] > 1
    assert identity["ppid"] > 1
    assert identity["ppid"] != identity["pid"]
    assert identity["start_sec"] > 0
    assert 0 <= identity["start_usec"] < 1_000_000
    assert identity["flags"] & 2
    assert identity["pgid"] > 1


def _checked_removal_seconds(seconds: object) -> None:
    """Preserve the five-second observation bound and reject non-finite values."""
    assert isinstance(seconds, (int, float))
    assert not isinstance(seconds, bool)
    assert math.isfinite(seconds)
    assert 0 <= seconds <= 5


def _checked_cancel_status(case: str, status: JsonObject) -> None:
    """Require native cancellation status without initialization of a held image."""
    assert status["state"] == "exited"
    assert status["signal"] == 9
    assert status["exit"] == -1
    assert status["reason"] == "cancel"
    assert status["traced"] is True
    if case.endswith("-held"):
        assert "target-initializer-ns=" not in status["output"]
        assert "target-entry" not in status["output"]
    else:
        assert "target-denials-ok" in status["output"]


def _checked_job_removal(trial: JsonObject) -> None:
    """EOF and broker death require automatic removal before the native timer."""
    assert trial["status"] is None
    assert trial["job_removed"] is True
    assert _is_integer(trial["native_proof_deadline_ns"])
    assert trial["native_proof_deadline_ns"] > 0


def checked_exec_lifecycle(trial: JsonObject) -> None:
    """Require independent traced identity and removal inside the original bound."""
    case, identity = trial["case"], trial["worker_identity"]
    _checked_birth_identity(identity)
    if case.endswith("-held"):
        assert identity["pgid"] != identity["pid"]
    else:
        assert identity["pgid"] == identity["pid"]
    _checked_removal_seconds(trial["observation_seconds"])
    if "cancel" in case:
        _checked_cancel_status(case, trial["status"])
    else:
        _checked_job_removal(trial)


def _checked_control_inputs(item: JsonObject, digest: JsonObject) -> None:
    """Enforce empty entitlements and exact role-specific input snapshots."""
    assert item["entitlements"].strip() == ""
    if item["name"] == "broker":
        assert item["signal_transport"] == "mach-exception-v1"
        digest["build_inputs"] = checked_inputs(item, BROKER_INPUTS)
    elif item["name"] in ("worker", "target"):
        digest["build_inputs"] = checked_inputs(item, ("control_probes.h",))


def _checked_artifact(item: JsonObject, source: str) -> JsonObject:
    """Preserve exact source and final signed binary digest checks."""
    assert item["source_sha256"] == sha256(SOURCE / source)
    assert "flags=0x10002(adhoc,runtime)" in item["signing"]
    assert "Signature=adhoc" in item["signing"]
    assert valid_digest(item["sha256"])
    return {"source_sha256": item["source_sha256"], "binary_sha256": item["sha256"]}


def checked_artifacts(name: str, artifacts: list[JsonObject]) -> JsonObject:
    """Require the exact artifact closure, source snapshots and final signed hashes."""
    sources = {"broker": f"{name}_broker.c", "worker": f"{name}_worker.c", "observer": "startup_observe.c"}
    if name == "control":
        sources["target"] = "control_target.c"
    assert len(artifacts) == len(sources)
    assert {item["name"] for item in artifacts} == set(sources)
    digests = {}
    for item in artifacts:
        digest = _checked_artifact(item, sources[item["name"]])
        if name == "control":
            _checked_control_inputs(item, digest)
        digests[item["name"]] = digest
    return digests


def _checked_header(name: str, report: JsonObject, context: JsonObject) -> None:
    """Validate the suite schema, native platform and mandatory repetition claim."""
    assert name in ("startup", "control")
    version = 1 if name == "startup" else 2
    assert report["schema_version"] == f"specfact-managed-{name}-experiment-v{version}"
    assert report["architecture"] == "arm64"
    assert report["os_build"] == context["os_build"]
    assert _is_integer(report["repetitions"])
    assert report["repetitions"] == 100


def _checked_flags(name: str, report: JsonObject) -> None:
    """Passing fixture proof must never claim production boundary approval."""
    assert report[f"{name}_subset_passed"] is True
    assert report["repetition_gate_passed"] is True
    assert report["production_approved"] is False
    assert report["signed_boundary_verified"] is False
    assert report["signing_mode"] == "ad-hoc"
    assert report["hardened_runtime"] is True


def _checked_counts(name: str, report: JsonObject) -> tuple[collections.Counter[str], dict[str, int]]:
    """Count actual successful trials independently of the receipt's gate flags."""
    trials = report["trials"]
    assert trials
    assert all(trial.get("passed") is True for trial in trials)
    races = STARTUP_RACES if name == "startup" else CONTROL_RACES
    field = "mode" if name == "startup" else "case"
    counts = collections.Counter(trial[field] for trial in trials if not trial.get("abandon_process_group"))
    expected: dict[str, int] = dict.fromkeys(races, 100)
    assert {race: counts[race] for race in races} == expected
    count_field = "completed_races" if name == "startup" else "completed_lifecycle_cases"
    assert report[count_field] == expected
    return counts, expected


def _checked_startup_trials(report: JsonObject, counts: collections.Counter[str]) -> None:
    """Startup retains its v1 controls, intentional survivor and exact profile."""
    assert all(counts[mode] == 1 for mode in ("normal", "runtime-trap"))
    assert report["probe_control"]["passed"] is True
    negative = [trial for trial in report["trials"] if trial.get("abandon_process_group")]
    assert len(negative) == 1
    assert negative[0]["survived"] is True
    assert report["profile_sha256"] == sha256(SOURCE / "fixture.sb")


def _checked_control_trials(
    trials: list[JsonObject], counts: collections.Counter[str], expected: dict[str, int]
) -> None:
    """Control v2 admits exactly the required protocol and lifecycle cases."""
    assert counts == collections.Counter({**expected, **dict.fromkeys(PROTOCOL_CASES, 1)})
    assert not any(trial.get("abandon_process_group") for trial in trials)
    for trial in trials:
        case = trial["case"]
        if not case.startswith("exec-"):
            continue
        if case in CONTROL_RACES:
            checked_exec_lifecycle(trial)
        elif case in PROTOCOL_CASES:
            checked_exec_protocol(trial)


def checked_receipt(name: str, report: JsonObject, context: JsonObject) -> JsonObject:
    """Reject incomplete fixed-fixture proof and export only explicit safe fields."""
    _require_assertions()
    _checked_header(name, report, context)
    _checked_flags(name, report)
    counts, expected = _checked_counts(name, report)
    if name == "startup":
        _checked_startup_trials(report, counts)
    else:
        _checked_control_trials(report["trials"], counts, expected)
    # No identities, capabilities, paths, status output or errors are published.
    checks = {
        "suite": name,
        "result": "passed",
        **context,
        "completed_races": expected,
        "repetition_gate_passed": True,
        "signing_mode": "ad-hoc",
        "hardened_runtime": True,
        "production_approved": False,
        "signed_boundary_verified": False,
        "helper_sha256": sha256(SOURCE / f"{name}.py"),
        "artifacts": checked_artifacts(name, report["artifacts"]),
    }
    if name == "startup":
        checks["profile_sha256"] = report["profile_sha256"]
    else:
        checks["protocol_checks"] = len(PROTOCOL_CASES)
    return checks


def _passed_case(trial: object, field: str) -> str | None:
    """Select only named, successful trials from bounded failure diagnostics."""
    if not isinstance(trial, dict) or trial.get("passed") is not True:
        return None
    case = trial.get(field)
    return case if isinstance(case, str) else None


def _completed_cases(trials: object, field: str, cases: set[str]) -> dict[str, int]:
    """The diagnostic record bound rejects oversized lists without truncation."""
    if not isinstance(trials, list) or len(trials) > 2048:
        return {}
    counts = collections.Counter(_passed_case(trial, field) for trial in trials)
    return {case: counts[case] for case in sorted(cases) if counts[case]}


def _receipt_diagnostics(name: str, path: Path, cases: set[str]) -> JsonObject:
    """Parse bounded failure receipts; never publish raw failure text."""
    try:
        if path.stat().st_size > 4 * 1024 * 1024:
            return {}
        report = json.loads(path.read_bytes())
        failure = report.get("failure", "")
        kind = failure.partition(":")[0] if isinstance(failure, str) else ""
        field = "mode" if name == "startup" else "case"
        return {
            "failure_type": kind if kind in _FAILURE_CLASSES else "unknown",
            "completed_cases": _completed_cases(report.get("trials", []), field, cases),
        }
    except (OSError, ValueError, AttributeError):
        return {}


def _owned_marker(line: str, allowed: set[str]) -> JsonObject | None:
    """Accept only an explicitly owned failure with a fixed case name."""
    try:
        item = json.loads(line)
    except ValueError:
        return None
    if not isinstance(item, dict) or item.get("failure_origin") is not True:
        return None
    case = item.get("failed_case")
    return item if isinstance(case, str) and case in allowed else None


def _worker_state_diagnostics(name: str, phase: str, item: JsonObject) -> JsonObject:
    """Only complete boolean wait observations may enter the public summary."""
    if name != "control" or phase != "request-wait":
        return {}
    state = item.get("last_worker_state")
    if not isinstance(state, dict):
        return {}
    fields = ("wait_accepted", "wait_pending", "worker_reaped", "output_closed")
    if not all(isinstance(state.get(field), bool) for field in fields):
        return {}
    return {"last_worker_state": {field: state[field] for field in fields}}


def _socket_diagnostics(name: str, phase: str, item: JsonObject) -> JsonObject:
    """Only fixed socket categories from their originating phase may be published."""
    if name != "control" or phase != "bootstrap-socket":
        return {}
    state = item.get("bootstrap_socket_state")
    if not isinstance(state, str) or state not in _SOCKET_STATES:
        return {}
    return {"bootstrap_socket_state": state}


def _marker_diagnostics(name: str, item: JsonObject) -> JsonObject:
    """Project one originating marker without borrowing later nested evidence."""
    phase = item.get("failure_phase")
    phase = phase if isinstance(phase, str) and phase in _FAILURE_PHASES else "unknown"
    return {
        "failed_case": item["failed_case"],
        "failure_phase": phase,
        **_worker_state_diagnostics(name, phase, item),
        **_socket_diagnostics(name, phase, item),
    }


def _log_diagnostics(name: str, path: Path, allowed: set[str]) -> JsonObject:
    """Select the first explicitly owned failure in the bounded private log tail."""
    try:
        with path.open("rb") as log:
            log.seek(max(0, path.stat().st_size - 16384))
            lines = log.read(16384).decode("utf-8", errors="replace").splitlines()
    except OSError:
        return {}
    for line in lines:
        item = _owned_marker(line, allowed)
        if item is not None:
            return _marker_diagnostics(name, item)
    return {}


def failure_summary(name: str, receipt_path: Path, log_path: Path) -> JsonObject:
    """Combine bounded allowlisted counts and the originating failure marker."""
    result = {"failure_type": "unknown", "failed_case": "unknown", "failure_phase": "unknown", "completed_cases": {}}
    cases: set[str] = set(STARTUP_RACES if name == "startup" else CONTROL_RACES + PROTOCOL_CASES)
    allowed = cases | {"protocol", "isolation-left", "isolation-right", "normal", "runtime-trap"}
    result.update(_receipt_diagnostics(name, receipt_path, cases))
    result.update(_log_diagnostics(name, log_path, allowed))
    return result


def run_suite(name: str, root: Path, context: JsonObject) -> JsonObject:
    """Run one bounded native suite and remove its private receipt and log."""
    receipt_path = root / f"{name}.json"
    log_path = root / f"{name}.log"
    category = "helper_failed"
    diagnostics = {}
    try:
        with log_path.open("wb") as log:
            process = subprocess.run(
                [sys.executable, "-B", str(SOURCE / f"{name}.py"), "--repetitions", "100", "--out", str(receipt_path)],
                stdout=log,
                stderr=subprocess.STDOUT,
                timeout=720,
                check=False,
            )
        if process.returncode == 0:
            category = "receipt_gate_failed"
            return checked_receipt(name, json.loads(receipt_path.read_text()), context)
    except subprocess.TimeoutExpired:
        category = "helper_timeout"
    except (OSError, ValueError, AssertionError, KeyError, TypeError, AttributeError, RuntimeError):
        category = "receipt_or_execution_failed"
    finally:
        diagnostics = failure_summary(name, receipt_path, log_path)
        # Raw receipts/logs are never printed or uploaded, including on failure.
        receipt_path.unlink(missing_ok=True)
        log_path.unlink(missing_ok=True)
    return {
        "suite": name,
        "result": "failed",
        "category": category,
        **diagnostics,
        "production_approved": False,
        "signed_boundary_verified": False,
    }


def main() -> int:
    """Run suites serially, publishing safe summaries and stopping on timeout."""
    _require_assertions()
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    os.umask(0o077)
    root = Path(os.environ["RUNNER_TEMP"]) / "specfact-macos-boundary"
    context = json.loads((root / "platform.json").read_text())
    passed = True
    with Path(os.environ["GITHUB_STEP_SUMMARY"]).open("a", encoding="utf-8") as summary:
        summary.write("Bounded startup/control fixtures; production flags remain false.\n\n")
        summary.write("| Suite | Result | Check SHA-256 |\n| --- | --- | --- |\n")
        for name in ("startup", "control"):
            _LOGGER.info("Starting %s: 100 repetitions, serial, 720-second ceiling.", name)
            checks = run_suite(name, root, context)
            digest = hashlib.sha256(json.dumps(checks, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
            _LOGGER.info("%s", json.dumps({**checks, "check_sha256": digest}, sort_keys=True))
            summary.write(f"| {name} | {checks['result']} | `{digest}` |\n")
            summary.flush()
            passed = passed and checks["result"] == "passed"
            if checks.get("category") == "helper_timeout":
                summary.write("Hard timeout: no further suite may start on this VM.\n")
                return 1
        summary.write("\nCI fixture evidence only; no runtime/install admission.\n")
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
